### ISSUE TITLE
Add themes

### ISSUE THREAD

**Issue by mountwebs** [mountwebs/folkestemmen#11]
With styled components and themeProvider.

**Comment by mountwebs** [comment]
https://css-tricks.com/theming-and-theme-switching-with-react-and-styled-components/

**Comment by carlos-ch** [comment]
could add normalize or some CSS reset

**Comment by carlos-ch** [comment]
https://dev.to/mikewheaton/theming-with-styled-components-19ce
make use of react-helmet
